# Try to find the SDL2 library
#  SDL2_FOUND - system has SDL2
#  SDL2_INCLUDE_DIR - the SDL2 include directory
#  SDL2_LIBRARY - the SDL2 library

FIND_PATH(SDL2_INCLUDE_DIR NAMES SDL2/SDL.h)
SET(_SDL2_STATIC_LIBS libSDL2.a)
SET(_SDL2_SHARED_LIBS libSDL2.dll.a SDL2)
IF(USE_STATIC_LIBS)
    FIND_LIBRARY(SDL2_LIBRARY NAMES ${_SDL2_STATIC_LIBS} ${_SDL2_SHARED_LIBS})
ELSE()
    FIND_LIBRARY(SDL2_LIBRARY NAMES ${_SDL2_SHARED_LIBS} ${_SDL2_STATIC_LIBS})
ENDIF()
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 DEFAULT_MSG SDL2_LIBRARY SDL2_INCLUDE_DIR)
MARK_AS_ADVANCED(SDL2_LIBRARY SDL2_INCLUDE_DIR)