# Try to find the VORBIS library
#  VORBIS_FOUND - system has VORBIS
#  VORBIS_INCLUDE_DIR - the VORBIS include directory
#  VORBIS_LIBRARY - the VORBIS library

FIND_PATH(VORBIS_INCLUDE_DIR NAMES vorbis/codec.h)
FIND_LIBRARY(VORBIS_LIBRARY NAMES libvorbis.a vorbis)
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Vorbis DEFAULT_MSG VORBIS_LIBRARY VORBIS_INCLUDE_DIR)
MARK_AS_ADVANCED(VORBIS_LIBRARY VORBIS_INCLUDE_DIR)
