# Try to find the OpenGLES librairy
#  OPENGLES_FOUND - system has OpenGLES
#  OPENGLES_INCLUDE_DIR - the OpenGLES include directory
#  OPENGLES_LIBRARY - the OpenGLES library

FIND_PATH(OPENGLES_INCLUDE_DIR NAMES GLES2/gl2.h)
FIND_LIBRARY(OPENGLES_LIBRARY NAMES GLESv2)
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenGLES DEFAULT_MSG OPENGLES_LIBRARY OPENGLES_INCLUDE_DIR)
MARK_AS_ADVANCED(OPENGLES_LIBRARY OPENGLES_INCLUDE_DIR)