# Try to find the PNG librairy
#  PNG_FOUND - system has PNG
#  PNG_INCLUDE_DIR - the PNG include directory
#  PNG_LIBRARY - the PNG library

FIND_PATH(PNG_INCLUDE_DIR NAMES png.h PATH_SUFFIXES libpng15 libpng)
FIND_LIBRARY(PNG_LIBRARY NAMES libpng15.a libpng.a png15 png)
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PNG DEFAULT_MSG PNG_LIBRARY PNG_INCLUDE_DIR)
MARK_AS_ADVANCED(PNG_LIBRARY PNG_INCLUDE_DIR)
