#ifndef OTCLIENT_CORE_CONST_H
#define OTCLIENT_CORE_CONST_H

enum ThingAttributesGroup {
    THING_GROUP_NONE = 0,
    THING_GROUP_GROUND,
    THING_GROUP_CONTAINER,
    THING_GROUP_WEAPON,
    THING_GROUP_AMMUNITION,
    THING_GROUP_ARMOR,
    THING_GROUP_RUNE,
    THING_GROUP_TELEPORT,
    THING_GROUP_MAGICFIELD,
    THING_GROUP_WRITEABLE,
    THING_GROUP_KEY,
    THING_GROUP_SPLASH,
    THING_GROUP_FLUID,
    THING_GROUP_DOOR,
    THING_GROUP_LAST
};

#endif
