#!/bin/bash
echo '-- generated by ./tools/gen_needed_translations.sh'
echo 'Locales.neededTranslations = {'
cat <(find \( -name "*.lua" -o -name "*.otui" \) -exec grep -oE "tr\\('(\\\\'|[^'])*'" {} \;) \
    <(find \( -name "*.lua" -o -name "*.otui" \) -exec grep -oE "tr\\(\"(\\\\\"|[^\"])*\"" {} \;) \
    | sort | uniq | sed "s/^tr(.\(.*\).$/  \"\1\",/"
echo '}'
